### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by tderflinger** [rodneyknaap/atx-286at-v1-mainboard#2]
Hi Rodney,

Thanks for sharing this great project. Would you be interested in creating a documentation / education website for this project?
I have knowledge in web development and could help out.

We could host the website for free right here on GitHub.

A documentation website could really enhance the usefulness of your designs and help students and other interested people learn more about 286 technology.

Please let me know your thoughts.

Thanks and best regards,
-Thomas

**Comment by rodneyknaap** [comment]
Hi Thomas,

Thanks for your suggestion, it's a great idea to add educational pages to this project. I have thought about the educational value of my work as well since I have had to do an extreme deep dive into the 286 functions because of designing my own system and CPU command and control mechanisms. This is about as deep as you can go into the 286 from the hardware angle.

Also, I have noticed somewhere that GitHub offers website hosting which is a great feature to integrate into my projects.

I have thought a little further in what would be involved to create such a website. What it boils down to is to conceive and write the content in the form of small articles or chapters which can be presented in the form of indexed pages which can be browsed on topics which can form subject areas. Writing this content will be the biggest part time-wise. 

Besides this I could write articles based on my work and various experiences while developing the project. This kind of insider look into the development would have some practical value for future designers. Basically something similar to my VCF thread about the project, except more organized and indexed so it can be browsed more like a digital documentation.

What I hope is that more people will get excited about the historic technological legacy which is ours as a civilization in this world. And that new computer users learn to understand why this legacy is so important, as not to let modern popular commercial marketing concepts by themselves be responsible for forming the IT insight of students, but for them to also understand the essence of what IT is at its core. For which of course the IBM PC/AT has been a huge factor to enable the PC industry standard to gain momentum. Clone builders took over the development, however without IBM creating this design, we would not have any PCs in this world as we know them.

I hope that when time passes, PC technology will be more respected and appreciated.
What I am still seeing very often is the dated opinions of the time period about the 286, but that is simply from a buyer/user's perspective and not a pure scientific or historic value view on the subject matter, which is what I am really interested in, and the reason for all my research and work.

I will look into this myself first, and I will keep your offer for help in mind which is very kind of you. When I have some better idea how you could assist, I will contact you, okay?

First I need to get some things off my plate which I am dealing with right now. One thing is concluding the final PCB designs for this project, the second is to complete my 286/486 project far enough so I have a complete schematic and PCB concept so I will be able to order the PCBs manufactured and I can start the practical phase of that project's development. Right now time is a factor so I get the work done whenever I can.

I will think about filling the time gaps by writing a series of articles with diagrams and such so I can get some material for the educational/informational website.

This project is so broad and complex that it can benefit a lot from organized documentation. So far I have done this in the main intro page, but an indexed web page would really be the best way to gain an overview and would be somewhat easier to navigate.

Any ideas or suggestions you can share here in the conversation or contact me by email is also fine.

Kind regards,

Rodney

**Comment by tderflinger** [comment]
Hello Rodney,

Thanks a lot for your extensive answer. I have the perspective of programmer who is also interested in learning electronic design. For this reason I got interested in your project, because I think it can help people understand hardware design better. That you share your knowledge with the world is very kind.

I have some ideas regarding the documentation site, that I could help with once you have written the content. For example, I think the image of the PCB board with the components could be made interactive. When users click on a component they get more detailed information about the individual component.

Another area that would be interesting is how electronic designers share their work on the web. For example, how is the information open source electronic design applications like KiCad produce shared on the web so that interested designers can easily reuse and study it? Would it be feasible to integrate a simulator of the PCB and its components in the documentation webpage? How can we share the BOM on the web? What web renderers exist for the different electronic design formats? 
This is more the perspective a web programmer has when getting into electronics.

In order to investigate these topics it would be interesting to know which applications did you use when designing the PCB board? Did you use open source software?

Once you have written your documentation content feel free to reach out to me in case you need help with the website.

Thanks and all the best,
-Thomas

**Comment by tderflinger** [comment]
Just wanted to add a link that might be useful when writing the documentation: https://diataxis.fr

**Comment by rodneyknaap** [comment]
Hello Thomas,

Thanks for elaborating your thoughts and suggestions, it's very kind and I appreciate your ideas. If the information I would write could be presented in interesting new ways through website programming that does present new concepts which would benefit the information provided by the project, I see the potential there.

I will give the documentation and writing articles and content some more thought when I have time.

I will keep your suggestions in mind Thomas, there is a lot of development work ahead and I am also currently working on the final revision designs to conclude this project.

Kind regards,

Rodney
